service: udia-gql
app: udia
tenant: awwong1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  tableName: 'users-${self:service}-${opt:stage, self:provider.stage}'
  serverless-offline:
    host: 0.0.0.0
  dynamoDbEndpoint:
    prod: ''
    dev: 'http://localhost:8000'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ca-central-1'}
  logRetentionInDays: 14
  apiKeys:
    - ${self:provider.stage}-gqlEndpointKey
  environment:
    USERS_TABLE: ${self:custom.tableName}
    DYNAMODB_ENDPOINT: ${self:custom.dynamoDbEndpoint.${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    events:
      - http:
          method: get
          path: hello
  graphql:
    handler: handler.graphql
    memorySize: 192
    timeout: 9
    events:
      - http:
          method: ANY
          path: graphql
          cors: true

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .gitignore
    - .DS_Store
    - npm-debug.log
    - .serverless/**
    - .serverless_plugins/**
    - coverage/**
    - .circleci/**
    - .vscode/**
    - .dockerignore
    - Dockerfile
    - docker-compose.yml
    - init_local_dynamodb.sh
    - README.md
