service: udia-gql
app: udia
tenant: awwong1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  usersTable: 'users-${self:service}-${opt:stage, self:provider.stage}'
  serverless-offline:
    host: 0.0.0.0
  dynamoDbEndpoint:
    prod: ''
    dev: 'http://localhost:8000'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  cfnRole: arn:aws:iam::593583987155:role/Serverless_CloudFormation
  logRetentionInDays: 14
  environment:
    USERS_TABLE: ${self:custom.usersTable}
    DYNAMODB_ENDPOINT: ${self:custom.dynamoDbEndpoint.${self:provider.stage}}
    DYNAMODB_REGION: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.usersTable}"

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.usersTable}

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    events:
      - http:
          method: get
          path: hello
  graphql:
    handler: handler.graphql
    memorySize: 192
    timeout: 9
    events:
      - http:
          method: ANY
          path: graphql
          cors: true
