version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/udia-gql
    docker:
      - image: circleci/node:8.16.0
    steps:
      - checkout
      - run:
          name: Update npm to Latest
          command: sudo npm install -g npm@latest
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Project Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    working_directory: ~/udia-gql
    docker:
      - image: circleci/node:8.16.0
      - image: circleci/dynamodb:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Initialize Test Database
          command: npm run load_dev_db
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
      - codecov/upload

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /feature\/.*/
      - test:
          requires:
            - build
